name: Check

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV
      - name: "use node ${{ env.node_version }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node_version }}"

      - name: "Install bun & dependencies"
        uses: oven-sh/setup-bun@v1
        with:
          run_install: |
            - recursive: true
            - args: [--frozen-lockfile]

      - name: Lint check
        run: bun run lint
      - name: Format check
        run: bun run prettier
      - name: Unit & Integration tests
        run: bun run test
      - name: Smoke & Acceptance tests
        run: |
          bun run build-storybook --quiet
          bun playwright install
          bun dlx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "bun dlx http-server storybook-static --port 6006 --silent" \
            "bun dlx wait-on tcp:127.0.0.1:6006 && bun run test-storybook"
