name: Check

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV
      - name: "use node ${{ env.node_version }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node_version }}"

      - name: "Install bun & dependencies"
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Create build env file
        run: |
          cat > .env.build << EOL
          ANALYZE=false
          BETTER_AUTH_SECRET="ci-dummy-secret-key-for-build-only"
          BETTER_AUTH_URL="http://localhost:5151"
          NEXT_PUBLIC_BETTER_AUTH_URL="http://localhost:5151"
          EOL
          cp .env.build .env

      - name: Lint check
        run: bun run lint:check
      - name: Format check
        run: bun run prettier
